feat: build - deploy - ai comment
nventive/cloud-template pull request #14
Opened 2024-12-16 16:03 UTC by MounirAbdousNventive

GitHub Issue: #

## Proposed Changes

 - [ ] Bug fix
 - [ ] Feature
 - [ ] Code style update (formatting)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build or CI related changes
 - [ ] Documentation content changes
 - [ ] Other, please describe:

## What is the current behavior?

## What is the new behavior?

## Checklist

Please check that your PR fulfills the following requirements:

- [ ] Documentation has been added/updated.
- [ ] Automated tests for the changes have been added/updated.
- [ ] Updated [BREAKING_CHANGES.md](../BREAKING_CHANGES.md) (if you introduced a breaking change).

## Other information

2024-12-18 18:42 UTC, GabrielLetourneau requested changes
Parts about pipeline tooling will have to be rebased on top of what was done for Cree.

2024-12-20 15:14 UTC, MatFillion commented on template/azure-pipeline/azure-pipelines.yml
> +    value: "9.x"
in azure-pipelines.yml we set 9.0.x, should they match?

2025-01-10 14:59 UTC, MatFillion approved these changes

2025-02-20 17:22 UTC, francoisalbert approved these changes

2025-02-20 18:10 UTC, GabrielLetourneau approved these changes

2025-02-20 18:37 UTC, merged