feat(311925): Import migrations + Feature based structure + .Net 9
nventive/cloud-template pull request #7
Opened 2024-11-08 16:39 UTC by alexmaude

## Proposed Changes
 - [X] Feature

## Description
- Migration project runs by AppHost
- Script to create new migrations
- Core project for feature based services/repositories/models
- Endpoints structure
- Update to .Net 9.0
- Update packages

2024-11-14 16:15 UTC, MatFillion approved these changes

2024-11-15 15:12 UTC, francoisalbert commented on template/src/Placeholder.AppHost/Program.cs
> +var postgres = builder
On devrait pas sortir tout ce qui est Postgres dans un fichier a part? Selon moi si tu veux retirer postgres de ton projet, tu devrais avoir 1-2 lignes de code a changer dans le program.cs

2024-11-15 15:18 UTC, francoisalbert requested changes
We should make sure to isolate postgres for simple removal (and pattern to use when adding other services)

2024-11-15 18:53 UTC, lacheteau-s commented on template/src/Placeholder.AppHost/Program.cs
> +const string contestDbName = "weather";
Le nom `contest` n'est-il pas spécifique au contexte de Keep It Local?

2024-11-20 00:31 UTC, francoisalbert approved these changes

2024-11-20 14:57 UTC, merged